[package]
name = "tui-lab-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { version = "1", features = ["time", "rt", "rt-multi-thread", "macros", "sync"] }
regex = "1"
