[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tui-lab/tuilab"
rust-version = "1.75"

[workspace.lints.rust]
warnings = "deny"

[profile.release]
strip = true
