[package]
name = "tui-lab-snapshots"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
tui-lab-terminal = { path = "../terminal" }
